name: CI/CD pipline

on:
  push:
    branches: 
      - main

jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pandafairy/my_project:latest
  
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_HOST_IP }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_ACCESS_KEY }}
          port: 22
          script: |
            export CONTINER_NAME=${{ secrets.CONTAINER_NAME }}
            docker pull pandafairy/my_project:latest
            docker stop \$CONTAINER_NAME
            docker run -p 8080:3000 -d --env-file ~/.env --rm --name \$CONTAINER_NAME pandafairy/my_project:latest